server:
  port: 8010
  servlet:
    context-path: /link

spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      druid:
          url: jdbc:mysql://localhost:3306/bpms-test?serverTimezone=UTC
          username: root
          password: 123456
          initial-size: 10
          max-active: 100
          min-idle: 10
          max-wait: 60000
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  config: classpath:logback-spring.xml


